import Flapjack.PanSteppedSemantics
import Flapjack.RiscV.PanSemantics
import Flapjack.RiscV.PanMemory
import Guest.Basic
import Guest.Ast
import Guest.SoftwareAst
import Guest.Accel

/-!
# The guest as a flapjack program: state, handlers, and the stepped run

Everything here is computable, so it doubles as an executable model
(`lake exe run-guest`). The goal stated about it lives in `Guest.StepBound`.

* The program is `guestAst` (`Guest/Ast.lean`), the committed output of
  flapjack's Pancake parser on `Guest/guest.pp.pnk`, the cpp-expanded
  `ZISK_ACCEL` build (the deployed one: crypto via accelerator `@ffi` calls),
  regenerated by `tools/gen-guest-ast.sh`. `Guest.Software.guestAst`
  (`Guest/SoftwareAst.lean`) is the default build with all crypto in Pancake.
  `Guest.AstParse` proves once that the parser produces exactly these ASTs, so
  nothing here depends on the parser.
* `guestInitialState` lays the host input out per `guest/src/config.h` and
  zero-fills the output, scratch and heap regions.
* `guestPrimitiveHandler` is flapjack's own 64-bit `__add_with_carry__`.
* `guestFfiHandler` accepts the two foreign calls of the software build,
  `@halt` and `@trap`, as no-ops on the Pancake state. `guestMemoryFfi`
  (`Guest/Accel.lean`) additionally gives the accelerator calls of the
  `ZISK_ACCEL` build their ZisK semantics on memory.
* `guestMemoryAccess` selects CakeML's aligned-cell model for sub-word and
  shared-memory accesses, with the RISC-V little-endian byte layout.

## Status of the accelerated run

Flapjack's stepped semantics only take a locals-only `PanValueFfiHandler`, so
`guestMemoryFfi` cannot be attached yet and the accelerated guest cannot be
executed (flapjack #517). Until that lands, `runGuestStepped` runs the
software build; its docstring records the intended definition.

## Modelling caveats

* *`@halt` / `@trap` return.* On the machine both stop execution. Here the
  handler returns and the program continues: after `@halt` that is only the
  final `return`; after `@trap` (via `trap_with`) the callers keep going down
  their error paths, so the model may count steps the machine never takes.
  This only over-approximates, which is the safe direction for a bound.
* *Shared memory is in-map.* CakeML routes `!ld*`/`!st*` through the FFI
  oracle; flapjack (since PR 403) reads and writes the same memory map with
  the access size honoured. That is what puts the host input at `INPUT_ADDR`
  and lets the guest read it.
-/

namespace Guest

open Flapjack

/-! ### The program -/

/-- Entry point of the guest (`fun 1 main()` in `guest/src/main.pnk`). -/
def guestEntry : FunName := "main"

/-! ### The memory contract (`guest/src/config.h`) -/

/-- `INPUT_ADDR`: 8 bytes of zero metadata. -/
def inputAddr : Word := 1073741824
/-- `INPUT_LEN_ADDR`: 8-byte little-endian blob length. -/
def inputLenAddr : Word := 1073741832
/-- `INPUT_DATA_ADDR`: the blob, zero padded to a multiple of 8 bytes. -/
def inputDataAddr : Word := 1073741840
/-- `OUTPUT_ADDR`: start of the public output region. -/
def outputAddr : Word := 2684420096
/-- `HEAP_BASE`: the Pancake heap start, `@base`. -/
def heapBase : Word := 2701131776
/-- `HEAP_END`: end of the Pancake heap. -/
def heapEnd : Word := 2952790016
/-- `WORD`: bytes per word. -/
def bytesInWord : Word := 8

/-- Little-endian word from the first eight bytes of a list, zero padded. -/
def leWord (bytes : List (BitVec 8)) : Word :=
  (bytes.take 8).foldr (fun byte acc => (acc <<< 8) ||| byte.zeroExtend 64) 0

/-- The `k`-th little-endian word of the input blob. -/
def inputWord (input : InputBlob) (k : Nat) : Word :=
  leWord (input.drop (8 * k))

/-- Initial memory: the input region as the host lays it out, and the output,
scratch and heap regions (`[OUTPUT_ADDR, HEAP_END)`) zero-filled; every other
address is unmapped. Input words sit only at 8-byte strides from
`INPUT_DATA_ADDR`, which is how `input_blob` reads them (`!ldw`). -/
def guestInitialMemory (input : InputBlob) : Word → Option (PanValue Word) :=
  fun address =>
    let length : Word := BitVec.ofNat 64 input.length
    if address = inputAddr then some (.word 0)
    else if address = inputLenAddr then some (.word length)
    else if inputDataAddr ≤ address ∧ address < inputDataAddr + length ∧
        (address - inputDataAddr).toNat % 8 = 0 then
      some (.word (inputWord input ((address - inputDataAddr).toNat / 8)))
    else if outputAddr ≤ address ∧ address < heapEnd then some (.word 0)
    else none

/-- Initial program state for a run on `input`. Declarations are evaluated by
`evalPanValueSteppedProgram` itself, so the declaration tables start empty. -/
def guestInitialState (input : InputBlob) : PanValueProgramState Word :=
  { structs := []
    globals := fun _ => none
    functions := []
    returnShapes := []
    exceptions := []
    memory := guestInitialMemory input
    baseAddress := heapBase
    topAddress := heapEnd
    bytesInWord := bytesInWord }

/-! ### Host handlers -/

/-- Semantics of Pancake primitive operations (`__add_with_carry__`) on 64-bit
words, as defined by flapjack. -/
def guestPrimitiveHandler : PanPrimitiveHandler Word :=
  RiscV.panPrimitiveHandler

/-- Host side of the guest's foreign calls in the software build,
`@halt(@base, 0, @base, 0)` and `@trap(@base, code, @base, 0)`
(`guest/runtime/start.S`). Neither touches Pancake-visible state, so both leave
the locals unchanged; see the module docstring for the fact that on the machine
neither returns. Any other foreign call is unmodelled. -/
def guestFfiHandler : PanValueFfiHandler Word :=
  fun function _ _ _ _ locals =>
    if function == "halt" || function == "trap" then some locals else none

/-- Sub-word and shared-memory accesses follow CakeML's aligned-cell model with
the RISC-V byte layout: `ld8`/`st8`/`ld32`/`st32` and `!ld*`/`!st*` extract or
patch bytes of the aligned word cell (`Flapjack.RiscV.panRiscVMemoryModel`). -/
def guestMemoryAccess : PanValueMemoryAccess Word :=
  panValueMemoryAccessOfModel RiscV.panRiscVMemoryModel

/-! ### The run -/

/-- Step-counted run of the software guest `Guest.Software.guestAst` on
`input` with recursion guard `fuel`. -/
def runGuestSoftwareStepped (input : InputBlob) (fuel : Nat) :
    Option (PanValueSteppedResult Word) :=
  evalPanValueSteppedProgram (guestInitialState input) guestPrimitiveHandler
    guestFfiHandler fuel Software.guestAst guestEntry [] (memoryAccess := some guestMemoryAccess)

/-- Step-counted run of the guest on `input` with recursion guard `fuel`.

Intended: the accelerated `guestAst` with `guestMemoryFfi` handling the
accelerator calls. Blocked on flapjack #517 (the stepped semantics need an
`ExtCall` handler that can write memory); until then this is the software
run, whose Pancake step counts are far larger (all crypto in software). -/
def runGuestStepped (input : InputBlob) (fuel : Nat) :
    Option (PanValueSteppedResult Word) :=
  runGuestSoftwareStepped input fuel

end Guest
