import Flapjack.PanSteppedSemantics
import Flapjack.RiscV.PanSemantics
import Guest.Ast

/-!
# Goal 1: the guest terminates within a constant number of Pancake steps

The stateless guest (`guest/src/main.pnk`, cpp-expanded by `guest/build.sh`)
must terminate, and do so within a fixed number of source-level Pancake steps,
whenever the block it is asked to validate declares a gas limit of at most
`maxBlockGasLimit` (200M). The step count is the one produced by flapjack's
step-counted source semantics `Flapjack.evalPanValueSteppedProgram`.

Together with the step-preserving compilation theorem tracked in
<https://github.com/pirapira/flapjack/issues/352> (a fixed linear relation
between source steps and generated RISC-V instruction steps) this yields a
RISC-V step bound for the compiled guest.

## What is filled in

* The program is `guestAst` (`Guest/Ast.lean`), the committed output of
  flapjack's Pancake parser on `Guest/guest.pp.pnk`, the cpp-expanded
  translation unit regenerated by `tools/gen-guest-ast.sh` (default build: no
  `GUEST_DEBUG`, no `ZISK_ACCEL`). `Guest.AstParse` proves once that the
  parser produces exactly `guestAst`, so nothing here depends on the parser.
* `guestInitialState` lays the host input out per `guest/src/config.h` and
  zero-fills the output, scratch and heap regions.
* `guestPrimitiveHandler` is flapjack's own 64-bit `__add_with_carry__`.
* `guestFfiHandler` accepts the two foreign calls of the default build,
  `@halt` and `@trap`, as no-ops on the Pancake state.

## Modelling caveats (to resolve on the flapjack side or here)

* *Byte-granular memory.* `Flapjack.PanValues` keys memory by exact address
  and treats `ld8`/`st8`/`ld32`/`st32`/`!ldw`/`!st8` as whole-cell accesses,
  whereas CakeML's `mem_load_byte` aligns the address and extracts a byte. The
  guest relies on the latter (e.g. `input_blob` copies words with `st` and
  callers read them back with `ld8`), so under the current semantics the run
  fails at the first unaligned byte read of a word-stored cell. The step-counted
  semantics need a byte-faithful memory (flapjack has the pieces in
  `Flapjack.RiscV.PanMemory`) before `guest_terminates_within_step_bound` can
  be true as stated.
* *`@halt` / `@trap` return.* On the machine both stop execution. Here the
  handler returns and the program continues: after `@halt` that is only the
  final `return`; after `@trap` (via `trap_with`) the callers keep going down
  their error paths, so the model may count steps the machine never takes.
  This only over-approximates, which is the safe direction for a bound.

## What is still `sorry`

`declaredBlockGasLimit`, the constant `guestPancakeStepBound`, and the theorem.
-/

namespace Guest

open Flapjack

/-- Word type of the guest: 64-bit RISC-V words (`riscv64` target of `cake`). -/
abbrev Word := RiscV.Word 64

/-- Input bytes as supplied by the host at `INPUT_DATA_ADDR`. -/
abbrev InputBlob := List (BitVec 8)

/-! ### The program -/

/-- Entry point of the guest (`fun 1 main()` in `guest/src/main.pnk`). -/
def guestEntry : FunName := "main"

/-! ### The memory contract (`guest/src/config.h`) -/

/-- `INPUT_ADDR`: 8 bytes of zero metadata. -/
def inputAddr : Word := 1073741824
/-- `INPUT_LEN_ADDR`: 8-byte little-endian blob length. -/
def inputLenAddr : Word := 1073741832
/-- `INPUT_DATA_ADDR`: the blob, zero padded to a multiple of 8 bytes. -/
def inputDataAddr : Word := 1073741840
/-- `OUTPUT_ADDR`: start of the public output region. -/
def outputAddr : Word := 2684420096
/-- `HEAP_BASE`: the Pancake heap start, `@base`. -/
def heapBase : Word := 2701131776
/-- `HEAP_END`: end of the Pancake heap. -/
def heapEnd : Word := 2952790016
/-- `WORD`: bytes per word. -/
def bytesInWord : Word := 8

/-- Little-endian word from the first eight bytes of a list, zero padded. -/
def leWord (bytes : List (BitVec 8)) : Word :=
  (bytes.take 8).foldr (fun byte acc => (acc <<< 8) ||| byte.zeroExtend 64) 0

/-- The `k`-th little-endian word of the input blob. -/
def inputWord (input : InputBlob) (k : Nat) : Word :=
  leWord (input.drop (8 * k))

/-- Initial memory: the input region as the host lays it out, and the output,
scratch and heap regions (`[OUTPUT_ADDR, HEAP_END)`) zero-filled; every other
address is unmapped. Input words sit only at 8-byte strides from
`INPUT_DATA_ADDR`, which is how `input_blob` reads them (`!ldw`). -/
def guestInitialMemory (input : InputBlob) : Word → Option (PanValue Word) :=
  fun address =>
    let length : Word := BitVec.ofNat 64 input.length
    if address = inputAddr then some (.word 0)
    else if address = inputLenAddr then some (.word length)
    else if inputDataAddr ≤ address ∧ address < inputDataAddr + length ∧
        (address - inputDataAddr).toNat % 8 = 0 then
      some (.word (inputWord input ((address - inputDataAddr).toNat / 8)))
    else if outputAddr ≤ address ∧ address < heapEnd then some (.word 0)
    else none

/-- Initial program state for a run on `input`. Declarations are evaluated by
`evalPanValueSteppedProgram` itself, so the declaration tables start empty. -/
def guestInitialState (input : InputBlob) : PanValueProgramState Word :=
  { structs := []
    globals := fun _ => none
    functions := []
    returnShapes := []
    exceptions := []
    memory := guestInitialMemory input
    baseAddress := heapBase
    topAddress := heapEnd
    bytesInWord := bytesInWord }

/-! ### Host handlers -/

/-- Semantics of Pancake primitive operations (`__add_with_carry__`) on 64-bit
words, as defined by flapjack. -/
def guestPrimitiveHandler : PanPrimitiveHandler Word :=
  RiscV.panPrimitiveHandler

/-- Host side of the guest's foreign calls in the default build,
`@halt(@base, 0, @base, 0)` and `@trap(@base, code, @base, 0)`
(`guest/runtime/start.S`). Neither touches Pancake-visible state, so both leave
the locals unchanged; see the module docstring for the fact that on the machine
neither returns. Any other foreign call is unmodelled. -/
def guestFfiHandler : PanValueFfiHandler Word :=
  fun function _ _ _ _ locals =>
    if function == "halt" || function == "trap" then some locals else none

/-! ### The run and the goal -/

/-- Step-counted run of the guest `guestAst` on `input` with recursion guard
`fuel`. -/
def runGuestStepped (input : InputBlob) (fuel : Nat) :
    Option (PanValueSteppedResult Word) :=
  evalPanValueSteppedProgram (guestInitialState input) guestPrimitiveHandler
    guestFfiHandler fuel guestAst guestEntry []

/-- The block gas limit declared by the input: the `gas_limit` field of the
block header inside the SSZ-encoded stateless input (what `fork.pnk` reads
back as `BE_GAS_LIMIT`). `none` when the input does not decode. -/
def declaredBlockGasLimit (input : InputBlob) : Option Nat := sorry

/-- Largest declared block gas limit covered by the bound. -/
def maxBlockGasLimit : Nat := 200000000

/-- The constant: an upper bound on the number of Pancake source steps taken by
the guest on any input whose declared block gas limit is at most
`maxBlockGasLimit`. To be fixed by the proof. -/
def guestPancakeStepBound : Nat := sorry

/-- Termination of the stepped guest run within `bound` steps. -/
def TerminatesWithin (input : InputBlob) (bound : Nat) : Prop :=
  ∃ fuel result steps,
    runGuestStepped input fuel = some (result, steps) ∧ steps ≤ bound

theorem terminatesWithin_panSteppedTerminates {input : InputBlob} {bound : Nat}
    (h : TerminatesWithin input bound) :
    PanSteppedTerminates (runGuestStepped input) := by
  obtain ⟨fuel, result, steps, hrun, _⟩ := h
  exact ⟨fuel, result, steps, hrun⟩

/-- **Goal 1.** If the input declares a block gas limit of at most
`maxBlockGasLimit`, the guest terminates within `guestPancakeStepBound`
Pancake steps. -/
theorem guest_terminates_within_step_bound (input : InputBlob) (gasLimit : Nat)
    (hdeclared : declaredBlockGasLimit input = some gasLimit)
    (hle : gasLimit ≤ maxBlockGasLimit) :
    TerminatesWithin input guestPancakeStepBound := sorry

end Guest
