#!/usr/bin/env python3
"""gen_keccak.py -- regenerate guest/src/lib/keccak.pnk (unrolled Keccak-f[1600] round body).
Usage: tools/gen_keccak.py guest/src/lib/keccak.pnk"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pyref import _RC, _ROT

def lane(pfx, x, y): return f"{pfx}{x}{y}"
def rotl(e, r):
    return e if r == 0 else f"({e} #>> {64 - r})"

o = []
w = o.append
w("""/* lib/keccak.pnk -- Keccak-256 (Ethereum flavour: rate 136, pad 0x01..0x80,
   32-byte digest). Port of evm-asm/EvmAsm/Stateless/SpecRef/Crypto.lean
   (keccakPad, keccakAbsorbBlock, keccakAbsorb, keccak256); the permutation is
   Keccak-f[1600] on 25 little-endian 64-bit lanes, lane (x,y) at stp + 8*(x+5*y).
   GENERATED by tools/gen_keccak.py (round body fully unrolled); rotate-left by
   r is written as the Pancake rotate-right `#>> (64 - r)`. Do not hand-edit the
   round body. */

var 1 keccak_rc = 0;   /* 24 round constants, one word each */
var 1 keccak_st = 0;   /* 200-byte sponge state */
var 1 keccak_pad = 0;  /* 136-byte final-block scratch */

fun 1 keccak_init() {
  keccak_rc = alloc(192);
  keccak_st = alloc(200);
  keccak_pad = alloc(136);""")
for i, rc in enumerate(_RC):
    v = rc if rc < (1 << 63) else rc - (1 << 64)
    w(f"  st keccak_rc + {8*i}, {v};")
w("  return 0;\n}\n")

w("/* Keccak-f[1600] on the 25-lane state at st. */")
w("fun 1 keccak_f1600(1 stp) {")
for y in range(5):
    for x in range(5):
        w(f"  var {lane('a',x,y)} = lds 1 (stp + {8*(x+5*y)});")
w("  var r = 0;")
w("  while r < 24 {")
# theta
for x in range(5):
    w(f"    var c{x} = " + " ^ ".join(lane('a',x,y) for y in range(5)) + ";")
for x in range(5):
    w(f"    var d{x} = c{(x-1)%5} ^ {rotl('c'+str((x+1)%5), 1)};")
# rho+pi+chi, plane by plane of the output: b[bx][by] = rotl(a[x][y]^d[x]) with y=bx, x=3*(by-3*bx)%5
for by in range(5):
    for bx in range(5):
        y = bx; x = (3*(by - 3*bx)) % 5
        assert (2*x+3*y) % 5 == by
        w(f"    var {lane('b',bx,by)} = {rotl(f'({lane('a',x,y)} ^ d{x})', _ROT[x+5*y])};")
    for bx in range(5):
        p, q = lane('b',(bx+1)%5,by), lane('b',(bx+2)%5,by)
        w(f"    var {lane('n',bx,by)} = {lane('b',bx,by)} ^ (({p} | {q}) ^ {p});")
for y in range(5):
    for x in range(5):
        w(f"    {lane('a',x,y)} = {lane('n',x,y)};")
w("    a00 = a00 ^ (lds 1 (keccak_rc + r * 8));")
w("    r = r + 1;")
w("  }")
for y in range(5):
    for x in range(5):
        w(f"  st stp + {8*(x+5*y)}, {lane('a',x,y)};")
w("  return 0;\n}\n")

w("""/* XOR the 136-byte block at blk into the state, then permute. */
fun 1 keccak_absorb_block(1 stp, 1 blk) {
  var i = 0;
  if (blk & 7) == 0 {
    while i < 136 {
      st stp + i, (lds 1 (stp + i)) ^ (lds 1 (blk + i));
      i = i + 8;
    }
  } else {
    while i < 136 {
      st stp + i, (lds 1 (stp + i)) ^ LD_LE64(blk + i);
      i = i + 8;
    }
  }
  keccak_f1600(stp);
  return 0;
}

/* keccak256 of the n bytes at p, written to the 32 bytes at out. */
fun 1 keccak256(1 p, 1 n, 1 out) {
  var stp = keccak_st;
  memzero(stp, 200);
  var i = 0;
  while i + 136 <=+ n {
    keccak_absorb_block(stp, p + i);
    i = i + 136;
  }
  var rem = n - i;             /* 0 <= rem < 136 */
  memzero(keccak_pad, 136);
  memcpy(keccak_pad, p + i, rem);
  st8 keccak_pad + rem, 1;
  st8 keccak_pad + 135, (ld8 (keccak_pad + 135)) | 128;   /* 0x81 when rem == 135 */
  keccak_absorb_block(stp, keccak_pad);
  memcpy(out, stp, 32);        /* first four lanes, little-endian */
  return 0;
}""")
open(sys.argv[1],"w").write("\n".join(o)+"\n")
